DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS stat;

CREATE TABLE users (
    id INTEGER PRIMARY KEY,
    name TEXT NOT NULL
);

CREATE TABLE stat (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id INTEGER NOT NULL,
    created TEXT NOT NULL,
    total INTEGER NOT NULL,
    added INTEGER NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users (id)
);
